config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  resources :services_requests, only: [:new, :create]
end

app/models/services_request.rb
class ServicesRequest < ActiveRecord::Base
  validates_presence_of :name, :phone, :details
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/services_requests_controller.rb
class ServicesRequestsController < ApplicationController

  def new
    @services_request = ServicesRequest.new
  end

  def create
    @services_request = ServicesRequest.new(services_request_params)

    respond_to do |format|
      if @services_request.save
        format.html { redirect_to @services_request }
        format.json { render :show, status: :created, location: @services_request }
        format.js {}
      else
        format.html { render :new }
        format.json { render json: @services_request.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def services_request_params
    params.require(:services_request).permit(:name, :lastname, :phone, :email, :details)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    @services_request = ServicesRequest.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/services_requests_helper.rb
module ServicesRequestsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>E Cruz Control LTDA</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag asset_path('ecruz_logo.jpg') %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/services_requests/_form.html.erb
<%= simple_form_for(@services_request, url: services_requests_path, remote: boolean) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, label: false, placeholder: '* Nombre', input_html: { class: 'required' } %>
    <%= f.input :lastname, label: false, placeholder: 'Apellido'  %>
    <%= f.input :phone, label: false, placeholder: '* Teléfono', input_html: { class: 'required' } %>
    <%= f.input :email, type: :email, label: false, placeholder: 'Correo'  %>
    <%= f.input :details, type: :text, label: false, placeholder: '* Escribe el servicio que deseas recibir o solicita una cotización', input_html: { class: 'required' } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit , "Solicitar servicios", class: 'submit-services-request pull-right' %>
  </div>
<% end %>

<br>
<p><small>Los campos con (*) son requeridos</small></p>

app/views/services_requests/create.js.erb
// confirm file called
console.log("create.js.erb file");

// Clean inputs in the form
$('#services-form').html(<%= escape_javascript(render partial: 'services_requests/form', locals: { boolean: true }) %>)

app/views/services_requests/new.html.erb
<h1>Make a Service Request for us:</h1>

<%= render 'form', boolean: false %>

<%= link_to 'Back', services_requests_path %>

app/views/welcome/home.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>E Cruz Control de Plagas</title>

    <!-- Custom Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="#">E Cruz Control LTDA</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#about">Acerca de Nosotros</a>
                    </li>
                    <li>
                        <a href="#services">Nuestros Servicios</a>
                    </li>
                    <li>
                        <a href="#contact">Contáctenos</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    <!-- Header -->
    <a name="about"></a>
    <div class="intro-header">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <div class="logo-header-circle">
                          <img class="img-responsive header-logo-image" src=<%= image_url 'ecruz_logo2.png' %> alt="">
                        </div>
                        <h3>Brindar a personas, comercios, hoteles que necesitan eliminar una plaga la mejor solución permitiéndole controlar el problema apoyados en nuestra experiencia y trayectoria</h3>
                        <hr class="intro-divider">
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

    <!-- Page Content -->

	<a  name="services"></a>
    <div class="content-section-a">

        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Mantenimiento de Patios<br>y jardínes</h2>
                    <p class="lead">Brindamos mantenimiento preventivo y correctivo al patio de tu casa</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive radius" src=<%= image_url 'jardin.jpg' %> alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Control de Plagas</h2>
                    <p class="lead">Sabemos que lo más importante es la salud de los nuestros, por lo que nos ofrecemos para deshacernos de esas plagas tan insalubres por ti y tu familia</p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive" src=<%= image_url 'ecruz_logo.jpg' %> alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Nuestra experiencia y<br>trayectoria</h2>
                    <p class="lead">Nuestro personal cuenta con la capacidad técnica para tratar sus problemas tanto el manejo de plagas como el mantenimiento de patios y jardínes</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive radius" src=<%= image_url "control_de_plagas.jpg" %> alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

	<a  name="contact"></a>
    <div class="banner">

        <div class="container">

            <div class="row">
                <div class="col-lg-6">
                  <h2>Llama sin compromisos:</h2><br>
                  <div class="boxed-full-width">
                    <h4>Teléfonos:</h4><p>8939-5049 | 8588-4420 | 8417-4585</p>
                    <h4>Correo:</h4><p>ecruzlimitada@gmail.com</p>
                  </div>
                </div>

                <div class="col-lg-6">
                  <h2>Contacta nuestros servicios:</h2><br>
                  <p class="boxed-full-width">Mandanos tu información y a la mayor brevedad nos pondremos en contacto contigo para brindarte la mejor solución</p>
                  <br>

                  <div id="services-form">
                    <%= render partial: 'services_requests/form', locals: { boolean: true } %>
                  </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.banner -->

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="#">Inicio</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#about">Sobre Nosotros</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#services">Nuestros Servicios</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#contact">Contáctenos</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Derechos Reservados &copy; E Cruz Control L.T.D.A 2015. Todos los derechos reservados</p>
                </div>
            </div>
        </div>
    </footer>

    <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog">
      <div class="modal-header">
        <h3 class="modal-title text-center boxed radius">Solicitud exitosa</h3>
      </div>
      <div class="modal-body">
        <div class="col-md-12 banner radius">
          <p>La información se envío a un encargado de la empresa, a la mayor brevedad se le contactará para brindarle la mejor solución posible</p>
        </div>
      </div>
      <div class="modal-footer">
        <div class="col-md-12">
          <button class="btn close-modal-button" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
</body>

</html>